#!/bin/sh

# TODO look at this https://git.sr.ht/~leon_plickat/river-config/tree/master/item/river/init

. ~/.config/profile

kanshi -c ~/.config/kanshi/config-desktop &

terminal=alacritty
browser=firefox
editor="emacsclient -c -a emacs"
file_manager=pcmanfm
apps="rofi -show drun -show-icons -theme-str 'element-icon { size: 32; }'"
menu="~/bin/dmenu_run_history.sh ~/bin/drofi"
commands="~/bin/launch.sh ~/bin/drofi"

riverctl map normal Super+Shift Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super Down focus-view next
riverctl map normal Super Up focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super+Shift Down swap next
riverctl map normal Super+Shift Up swap previous
riverctl map normal Super S zoom
riverctl map normal Super I focus-output next
riverctl map normal Super+Shift I send-to-output next
riverctl map normal Super D toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super G spawn "$terminal"
riverctl map normal Super Return spawn "$terminal"
riverctl map normal Super Space spawn "$apps"
riverctl map normal Super B spawn "$browser"
riverctl map normal Super V spawn "$editor"
riverctl map normal Super E spawn "$file_manager"

riverctl map normal None XF86AudioLowerVolume spawn 'pamixer -d 5 && ~/bin/notify.sh "Volume: $(pamixer --get-volume-human)" audio-volume-high'
riverctl map normal None XF86AudioRaiseVolume spawn 'pamixer -i 5 && ~/bin/notify.sh "Volume: $(pamixer --get-volume-human)" audio-volume-high'
riverctl map normal None XF86AudioMute spawn 'pamixer -t && ~/bin/notify.sh "Volume: $(pamixer --get-volume-human)" audio-volume-high'
riverctl map normal None XF86AudioPlay spawn "~/bin/playerctl.sh play-pause"
riverctl map normal None XF86AudioPrev spawn "~/bin/playerctl.sh previous"
riverctl map normal None XF86AudioNext spawn "~/bin/playerctl.sh next"
riverctl map normal None XF86AudioRewind spawn "~/bin/playerctl.sh rewind"
riverctl map normal None XF86AudioForward spawn "~/bin/playerctl.sh forward"

int_to_tag() {
    echo $((1 << ($1 - 1)))
}

for i in $(seq 1 9); do
    tags=$(int_to_tag $i)
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

mice="pointer-1133-16500-Logitech_G305"
for m in "$mice"; do
    riverctl input $m accel-profile flat
done

riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 32 400
riverctl xcursor_theme capitaine-cursors-white 24

riverctl border-color-focused 0x33ccff
riverctl border-color-unfocused 0x595959
riverctl border-width 4

riverctl rule-add '-app-id' '*' ssd
riverctl rule-add '-app-id' 'org.keepassxc.KeePassXC' tags $(int_to_tag 5)

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-location right -main-ratio 0.5 &

NIX_KWALLET_PAM=/etc/kwallet-pam-path
if [ -f "$NIX_KWALLET_PAM" ]; then
    $(cat $NIX_KWALLET_PAM)/libexec/pam_kwallet_init --unset QT_PLUGIN_PATH &> ~/sandbox/pam_kwallet_init.log
fi
dunst &
waybar -c ~/.config/waybar/config-river &
nm-applet &

riverctl focus-output DP-2
riverctl send-layout-cmd rivertile "main-location bottom"

[ -z "$(pidof keepassxc)" ] && keepassxc &
[ -z "$(pidof nextcloud)" ] && nextcloud &
xrdb ~/.config/X11/Xresources
xrdb -merge ~/.config/X11/Xresources-wayland
swaybg -o DP-1 -m fill -i ~/drive/pictures/wallpapers/zQbYocwXGY.png &
swaybg -o DP-2 -m fill -i ~/drive/pictures/wallpapers/wp5513064-vertical-anime-wallpapers.jpg &
swayidle -w &

riverctl focus-output DP-1
