#!/bin/sh

bspc rule -r "*"

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width 1
#bspc config border_width 0
bspc config window_gap 0
bspc config -d 0 window_gap 16
bspc config -d 5 window_gap 16
bspc config bottom_padding 27
bspc config top_padding 0
bspc config right_padding 0
bspc config left_padding 0

bspc config normal_border_color "#31363b"
bspc config active_border_color "#31363b"
bspc config focused_border_color "#fba922"
bspc config presel_feedback_color "#fba922"
# bspc config focused_border_color "#3daee9"
# bspc config presel_feedback_color "#3daee9"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle       true
#bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
bspc config pointer_action1 "move"
bspc config pointer_action2 "none"
bspc config pointer_action3 "resize_corner"
bspc config click_to_focus       "any"
bspc config initial_polarity "second_child"
#bspc config automatic_scheme     "spiral"
bspc config automatic_scheme     "alternate"
#bspc config automatic_scheme     "longest_side"
bspc config removal_adjustment true

#bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Steam state=floating
bspc rule -a Lutris state=floating
bspc rule -a guvcview state=floating

#bspc config external_rules_command "$(which external_rules)"
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a jetbrains-studio state=floating

~/bin/bspwm/autostart.sh &

