#!/bin/sh

wid=$1
class=$2
instance=$3

#desktop=$(bspc query -D -d --names)
#if [ $(bspc query -N -d | wc -l) -eq 0 ] ; then
#	echo "desktop=^$desktop border=off"
#else
#	echo "desktop=^$desktop border=on"
#fi
