#!/bin/sh

wid=$1
class=$2
instance=$3
conseq=$4

# _dynamic_spawn() {
# 	# masters=$(bspc query -N @/1 -n '.descendant_of.window')
# 	dest=$(bspc query -N @/1 -n '.descendant_of.window' | head -n1)
# 	bspc node $dest -p north
# 	echo "node=${dest}"
# }

# desktop=$(bspc query -D -d --names)
# if [ $desktop -eq 5 ] ; then
# 	_dynamic_spawn
# fi

receptacles=$(bspc query -N -n '.local.!window.leaf')
if [ -n "$receptacles" ] ; then
	dest=$(echo $receptacles | tail -n1)
	echo "node=${dest}"
fi

# dynamic=6
# deskfoc=$(bspc query -D -d --names)
# nodecount=$(bspc query -N -n '.window.local' | wc -l)
# if [ "$dynamic" = "$deskfoc" ] && [ $nodecount -gt 1 ] ; then
# 	dest='@/2'
# 	dir=north
# 	echo "node=${dest} split_dir=${dir}"
# fi
